require "plugins"
require "settings"

require "lualine-config"
require "treesitter-config"
require "lsp-config"
require "cmp-config"
require "autopairs-config"
require "nvimtree-config"
require "nvim-web-devicons-config"
